### ISSUE TITLE
运行失败并且游戏画面卡住

### ISSUE THREAD

**Issue by Schliechen** [qilishidai/ClashOfClansResourceRaid#1]
我已经按照说明正常配置了模拟器窗口以及py，但是运行后
![QQ截图20240815171534](https://github.com/user-attachments/assets/cc08f0fa-1bcc-474e-b134-b2a8e2ce9833)
圣水金币识别失败，并且打开战斗失败，游戏会卡住不动

**Comment by Schliechen** [comment]
我看了下“常用函数.py”中有报错“未解析的引用 'cv2'”
![aaa](https://github.com/user-attachments/assets/afab40b9-66c6-4e11-bcf3-fb159a2a5fbf)

**Comment by Schliechen** [comment]
> 我看了下“常用函数.py”中有报错“未解析的引用 'cv2'” ![aaa](https://private-user-images.githubusercontent.com/169595534/358182833-afab40b9-66c6-4e11-bcf3-fb159a2a5fbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjI0OTcsIm5iZiI6MTcyMzcyMjE5NywicGF0aCI6Ii8xNjk1OTU1MzQvMzU4MTgyODMzLWFmYWI0MGI5LTY2YzYtNGUxMS1iY2YzLWZiMTU5YTJhNWZiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNVQxMTQzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzZiOGFkYmYxNmZmZThiMjYxYWNhNTE1ODhjNjliNTZjODVmNmY3NzkzYjg2N2RmZjUyZDJjMjFlOTBhYTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ax_eIiZtoVVhnC2kLOf8qdgM7RBl18S0NqVN5GVhQuE)

下了opencv-python，import了cv2，不报错了但照样无法正常使用脚本，一样的问题

**Comment by qilishidai** [comment]
> 我已经按照说明正常配置了模拟器窗口以及py，但是运行后
> ![QQ截图20240815171534](https://github.com/user-attachments/assets/cc08f0fa-1bcc-474e-b134-b2a8e2ce9833)
> 圣水金币识别失败，并且打开战斗失败，游戏会卡住不动

使用最新的代码，该问题已经修复了。
系统缩放要调到100%。

**Comment by Schliechen** [comment]
(自动回复)您好，邮件已收到，请静候回复:)

**Comment by Schliechen** [comment]
(自动回复)您好，邮件已收到，请静候回复:)
